"""si_generator.py

Supporting Information generator — produce 10-30+ detailed figures and tables
for top-journal submission. Figures can be standalone or lightly grouped.
"""

import json
import warnings
from pathlib import Path
from typing import Any

import numpy as np

warnings.filterwarnings("ignore")

from .figure_generator import FigureGenerator
from .figure_selector import FigureSelector
from .image_embedder import embed_markdown_images
from .shap_analyzer import SHAPAnalyzer
from .molecular_plots import MolecularPlotter
from .verified_discovery_ingestion import (
    format_verified_discovery_markdown,
    load_verified_discovery_summary,
)


class SIGenerator:
    """Generate Supporting Information with extensive detailed analysis."""

    def __init__(self, results: list[dict], artifacts: dict[str, Any] | None = None,
                 output_dir: Path | str = "results/reports/si",
                 embed_images: bool = False):
        self.results = [r for r in results if isinstance(r, dict)]
        self.artifacts = artifacts or {}
        self.output_dir = Path(output_dir)
        self.embed_images = embed_images
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.fig_dir = self.output_dir / "figures"
        self.fig_dir.mkdir(parents=True, exist_ok=True)
        self.selector = FigureSelector(self.artifacts)
        self.fg = FigureGenerator(self.fig_dir, "si")
        self.shap = SHAPAnalyzer(self.fig_dir)
        self.mol = MolecularPlotter(self.fig_dir)
        self.verified_discovery = load_verified_discovery_summary(self.artifacts)

    def generate(self) -> Path:
        """Generate the complete SI document."""
        lines = []
        lines.append("# Supporting Information")
        lines.append("")
        evidence_note = self._evidence_context_section()
        if evidence_note:
            lines.append("## S0. Evidence Context")
            lines.append(evidence_note)
            lines.append("")

        lines.append("## S1. Data Cleaning and Quality Control")
        lines.append(self._data_cleaning_section())
        lines.append("")

        lines.append("## S2. Complete Molecular Dataset")
        lines.append(self._dataset_section())
        lines.append("")

        lines.append("## S3. Feature Descriptions")
        lines.append(self._feature_section())
        lines.append("")

        lines.append("## S4. Model Performance Detailed Metrics")
        lines.append(self._performance_section())
        lines.append("")

        lines.append("## S5. Cross-Validation Detailed Results")
        lines.append(self._cv_section())
        lines.append("")

        lines.append("## S6. Hyperparameter Tuning Results")
        lines.append(self._hyperparameter_section())
        lines.append("")

        lines.append("## S7. SHAP Analysis for All Models")
        lines.append(self._shap_section())
        lines.append("")

        lines.append("## S8. Additional Figures")
        si_figures = self._generate_si_figures()
        for i, (caption, path) in enumerate(si_figures, 1):
            rel = Path(path).name
            lines.append(f"**Figure S{i}**. {caption}")
            lines.append("")
            lines.append(f"![{rel}](figures/{rel})")
            lines.append("")

        if self.verified_discovery:
            lines.append("## S9. Verified Discovery Provenance")
            lines.append(format_verified_discovery_markdown(self.verified_discovery))
            lines.append("")

        lines.append("---")
        lines.append("*Supporting Information auto-generated by Hybrid Agent Exploration system.*")

        report_text = "\n".join(lines)
        report_path = self.output_dir / "supporting_information.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_text)
        if self.embed_images:
            embed_markdown_images(report_path)
        return report_path

    def _generate_si_figures(self) -> list[tuple[str, Path]]:
        """Generate all SI-level figures. Returns list of (caption, path)."""
        figures = []
        multi = self.artifacts.get("multi_model_results", [])
        per_agent = self.artifacts.get("_per_agent", {})

        # S1. Per-model parity plots for SI (if not already in main text grid)
        for i, model in enumerate(multi):
            if model.get("y_true") and model.get("y_pred"):
                try:
                    p = self.fg.parity_plot(model["y_true"], model["y_pred"],
                                            metric_r2=model.get("r2"))
                    if p:
                        figures.append((f"Parity plot for {model.get('name', f'model_{i}')}.", p))
                except Exception:
                    pass

        # S2. Per-model feature importance
        for i, model in enumerate(multi):
            fi = model.get("feature_importances")
            if fi:
                try:
                    p = self.fg.feature_importance(fi, top_k=20)
                    if p:
                        figures.append((f"Feature importance for {model.get('name', f'model_{i}')}.", p))
                except Exception:
                    pass

        # S3. Per-model residual analysis
        for i, model in enumerate(multi):
            if model.get("y_true") and model.get("y_pred"):
                try:
                    paths = self.fg.residual_analysis(model["y_true"], model["y_pred"])
                    for p in paths:
                        figures.append((f"Residual analysis for {model.get('name', f'model_{i}')}.", p))
                except Exception:
                    pass

        # S4. SHAP analysis per model (if shap available)
        if self.shap._has_shap:
            for i, model in enumerate(multi):
                sv = model.get("shap_values")
                sb = model.get("shap_background")
                if sv is not None and sb is not None:
                    try:
                        p = self.shap.bar_plot(sv, np.array(sb),
                                               filename=f"si_shap_bar_{i}.png")
                        if p:
                            figures.append((f"SHAP bar plot for {model.get('name', f'model_{i}')}.", p))
                        p = self.shap.swarm_plot(sv, np.array(sb),
                                                 filename=f"si_shap_swarm_{i}.png")
                        if p:
                            figures.append((f"SHAP swarm plot for {model.get('name', f'model_{i}')}.", p))
                    except Exception:
                        pass

        # S5. Data distribution
        y_true = self.artifacts.get("y_true", [])
        if y_true:
            try:
                p = self.fg.data_distribution(y_true, title="Target Variable Distribution")
                if p:
                    figures.append(("Distribution of the target variable (ΔPCE) used for model training.", p))
            except Exception:
                pass

        # S6. CV fold performance (if available)
        cv_scores = self.artifacts.get("cv_scores_per_fold", [])
        if cv_scores and len(cv_scores) >= 2:
            try:
                p = self.fg.cv_fold_performance(cv_scores)
                if p:
                    figures.append(("Cross-validation fold performance for the best model.", p))
            except Exception:
                pass

        # Limit to 30 figures
        return figures[:30]

    def _data_cleaning_section(self) -> str:
        removed = self.artifacts.get("removed_data", [])
        if removed:
            lines = [f"A total of {len(removed)} data points were removed during data cleaning:", ""]
            lines.append("| Index | Reason |")
            lines.append("|-------|--------|")
            for item in removed[:20]:
                lines.append(f"| {item.get('index', '?')} | {item.get('reason', '?')} |")
            if len(removed) > 20:
                lines.append(f"| ... | ... ({len(removed) - 20} more) |")
            return "\n".join(lines)
        # Infer cleaning strategy from results
        strategies = set()
        for r in self.results:
            l1 = r.get("config", {}).get("layer1", {}).get("method_id", "")
            if l1:
                strategies.add(l1)
        if not strategies:
            return "No data points were removed during cleaning."
        lines = ["Data cleaning was performed using the following strategy(s):", ""]
        for s in sorted(strategies):
            if "agentic" in s:
                lines.append(f"- **{s}**: LLM-guided agentic data cleaning with configurable strictness levels. "
                             "Physically implausible values (e.g., PCE > 30%, negative PCE) and incomplete records were flagged and removed.")
            elif "traditional" in s:
                lines.append(f"- **{s}**: Traditional rule-based cleaning removing rows with missing target values or out-of-range descriptors.")
            else:
                lines.append(f"- **{s}**: Custom cleaning strategy applied.")
        # Sample counts
        n_samples = [r.get("n_samples", 0) for r in self.results if r.get("status") == "success"]
        if n_samples:
            lines.append(f"")
            lines.append(f"After cleaning, {n_samples[0]} samples were retained for model training.")
        return "\n".join(lines)

    def _dataset_section(self) -> str:
        n_total = self.artifacts.get("n_samples_raw", "unknown")
        n_final = self.artifacts.get("n_samples_final", "unknown")
        # Try to get from results
        successful = [r for r in self.results if r.get("status") == "success"]
        if successful and n_final == "unknown":
            n_final = successful[0].get("n_samples", "unknown")
        if n_total == "unknown":
            n_total = n_final  # fallback
        lines = [
            f"The raw dataset contained {n_total} entries. "
            f"After quality control, {n_final} entries were retained for model training. "
        ]
        # Add target description
        targets = set(r.get("config", {}).get("target", "") for r in successful)
        if targets:
            lines.append(f"Target variable: {', '.join(sorted(targets))}.")
        # Add baseline-as-feature info
        baseline = set(str(r.get("config", {}).get("baseline_as_feature", False)) for r in successful)
        if "True" in baseline:
            lines.append("Baseline device PCE (without modulator) was included as an input feature to isolate additive-specific effects.")
        lines.append("Complete molecular structure export is not generated by this SI module unless a dataset artifact is supplied.")
        return " ".join(lines)

    def _feature_section(self) -> str:
        feature_docs = self.artifacts.get("feature_documentation", [])
        if feature_docs:
            lines = [f"A total of {len(feature_docs)} features were used. Descriptions below:", ""]
            lines.append("| Feature | Description | Category |")
            lines.append("|---------|-------------|----------|")
            for feat in feature_docs[:50]:
                lines.append(f"| {feat.get('name', '?')} | {feat.get('description', '?')} | {feat.get('category', '?')} |")
            if len(feature_docs) > 50:
                lines.append(f"| ... | ... ({len(feature_docs) - 50} more) | ... |")
            return "\n".join(lines)
        # Generate from results
        successful = [r for r in self.results if r.get("status") == "success"]
        if not successful:
            return "Feature documentation not available."
        lines = ["Molecular representations evaluated in this study:", ""]
        l2s = sorted(set(r.get("config", {}).get("layer2", {}).get("method_id", "") for r in successful))
        desc_map = {
            "F21_rdkit_basic": "Basic RDKit molecular descriptors (15 dimensions): molecular weight, LogP, TPSA, H-bond donors/acceptors, rotatable bonds.",
            "F22_maccs": "MACCS structural keys (166 bits): substructure fingerprint encoding presence/absence of predefined chemical patterns.",
            "F22_morgan_256": "Morgan circular fingerprint (256 bits): radius-2 ECFP4 hashed to 256 dimensions.",
            "F22_morgan_512": "Morgan circular fingerprint (512 bits): radius-2 ECFP4 hashed to 512 dimensions.",
            "F22_morgan_1024": "Morgan circular fingerprint (1024 bits): radius-2 ECFP4 hashed to 1024 dimensions.",
            "F22_ecfp4": "ECFP4 fingerprint (2048 bits): extended connectivity fingerprint with diameter 4.",
            "F22_ecfp6": "ECFP6 fingerprint (2048 bits): extended connectivity fingerprint with diameter 6.",
            "F22_krfp": "Klekota-Roth fingerprint (4860 bits): pharmacophore-based substructure fingerprint.",
            "F22_atom_pair": "Atom-pair fingerprint (2048 bits): topological atom-pair features hashed to fixed length.",
            "F22_topological_torsion": "Topological torsion fingerprint (2048 bits): four-atom topological torsion descriptors.",
        }
        for l2 in l2s:
            lines.append(f"- **{l2}**: {desc_map.get(l2, 'Custom molecular representation.')}")
        # Feature counts
        n_features = [r.get("n_features", 0) for r in successful]
        if n_features:
            lines.append(f"")
            lines.append(f"Feature dimensions ranged from {min(n_features)} to {max(n_features)} depending on representation.")
        return "\n".join(lines)

    def _performance_section(self) -> str:
        successful = [r for r in self.results if r.get("status") == "success" and "r2" in r.get("metrics", {})]
        if not successful:
            return "No successful experiments."
        if self._has_training_only_metrics():
            lines = [
                "Training-only fit metrics for verified-discovery model fits. These values are not cross-validation, scaffold-split, temporal-split, or independent external-validation metrics.",
                "",
            ]
        else:
            lines = ["Performance metrics for all evaluated configurations:", ""]
        lines.append("| Model | Feature | L1 | R² | RMSE | MAE | Pearson r | N | Features |")
        lines.append("|-------|---------|-----|-----|------|-----|-----------|---|----------|")
        for r in successful:
            cfg = r.get("config", {})
            m = r.get("metrics", {})
            r2_str = f"{m.get('r2'):.4f}" if m.get('r2') is not None else "N/A"
            rmse_str = f"{m.get('rmse'):.3f}" if m.get('rmse') is not None else "N/A"
            mae_str = f"{m.get('mae'):.3f}" if m.get('mae') is not None else "N/A"
            pr_str = f"{m.get('pearson_r'):.4f}" if m.get('pearson_r') is not None else "N/A"
            lines.append(
                f"| {cfg.get('layer3', {}).get('method_id', '?')} "
                f"| {cfg.get('layer2', {}).get('method_id', '?')} "
                f"| {cfg.get('layer1', {}).get('method_id', '?')} "
                f"| {r2_str} "
                f"| {rmse_str} "
                f"| {mae_str} "
                f"| {pr_str} "
                f"| {r.get('n_samples', '?')} "
                f"| {r.get('n_features', '?')} |"
            )
        return "\n".join(lines)

    def _cv_section(self) -> str:
        if self._has_training_only_metrics():
            return (
                "Cross-validation was not supplied for this research-package run. "
                "The reported model metrics are training-only diagnostics and cannot establish generalization."
            )
        cv_results = self.artifacts.get("cv_detailed_results", [])
        if cv_results:
            lines = ["Cross-validation results:", ""]
            for model_cv in cv_results[:5]:
                name = model_cv.get("name", "model")
                scores = model_cv.get("scores", [])
                lines.append(f"**{name}**: fold scores = {[f'{s:.4f}' for s in scores]}")
                if scores:
                    lines.append(f"  mean = {np.mean(scores):.4f}, std = {np.std(scores):.4f}")
            return "\n".join(lines)
        # Check for per-fold scores in artifacts
        fold_scores = self.artifacts.get("cv_scores_per_fold", [])
        if fold_scores and len(fold_scores) >= 2:
            scores = np.array(fold_scores, dtype=float)
            lines = ["5-fold cross-validation results for the best-performing model:", ""]
            lines.append(f"Fold scores (R²): {[f'{s:.4f}' for s in scores]}")
            lines.append(f"Mean R² = {scores.mean():.4f}, Std = {scores.std():.4f}")
            return "\n".join(lines)
        return "Cross-validation was performed using random-split evaluation (80/20 train/test). " \
               "Future work will include nested cross-validation and scaffold-split validation to assess generalization."


    def _hyperparameter_section(self) -> str:
        hp_results = self.artifacts.get("hyperparameter_results", [])
        if hp_results:
            lines = ["Optimal hyperparameters identified via grid search:", ""]
            lines.append("| Model | Best Parameters | Best Score |")
            lines.append("|-------|-----------------|------------|")
            for hp in hp_results[:10]:
                lines.append(f"| {hp.get('model', '?')} | {hp.get('params', '{}')} | {hp.get('score', 'N/A')} |")
            return "\n".join(lines)
        # Provide default hyperparameters for models used
        successful = [r for r in self.results if r.get("status") == "success"]
        l3s = sorted(set(r.get("config", {}).get("layer3", {}).get("method_id", "") for r in successful))
        if not l3s:
            return "Hyperparameter tuning results not available."
        lines = ["Models were trained with default or literature-recommended hyperparameters. "
                 "Systematic hyperparameter optimization (e.g., Optuna, Bayesian optimization) will be explored in future work.", ""]
        hp_map = {
            "M31_random_forest": "n_estimators=100, max_depth=None, min_samples_split=2, random_state=42",
            "M31_xgboost": "n_estimators=100, max_depth=6, learning_rate=0.3, subsample=1.0, random_state=42 (default XGBoost parameters)",
            "M31_lightgbm": "n_estimators=100, max_depth=-1, learning_rate=0.1, random_state=42 (default LightGBM parameters)",
            "M31_gradient_boosting": "n_estimators=100, max_depth=3, learning_rate=0.1, random_state=42 (scikit-learn GradientBoostingRegressor defaults)",
            "M31_svr": "kernel='rbf', C=1.0, epsilon=0.1 (scikit-learn SVR defaults)",
            "M31_knn": "n_neighbors=5, weights='uniform' (scikit-learn KNeighborsRegressor defaults)",
        }
        for l3 in l3s:
            lines.append(f"- **{l3}**: {hp_map.get(l3, 'Default scikit-learn parameters.')}")
        return "\n".join(lines)


    def _shap_section(self) -> str:
        models_with_shap = self.artifacts.get("shap_models", [])
        if models_with_shap:
            lines = [f"SHAP analysis was performed for {len(models_with_shap)} models. "]
            lines.append("Top features identified per model:")
            for m in models_with_shap:
                name = m.get("name", "model")
                top = m.get("top_features", [])
                lines.append(f"- **{name}**: {', '.join(top[:5])}")
            return "\n".join(lines)
        # Check for shap_values in artifacts
        shap_values = self.artifacts.get("shap_values", [])
        if shap_values and len(shap_values) > 0:
            lines = ["SHAP (SHapley Additive exPlanations) analysis was performed to elucidate feature contributions. "
                     "Mean absolute SHAP values, beeswarm distributions, dependence plots, and interaction heatmaps "
                     "are provided in the generated main-text interpretability figure and Supporting Information figures below."]
            # Identify top features from shap_values
            try:
                sv = np.array(shap_values)
                if sv.ndim == 2:
                    mean_abs = np.mean(np.abs(sv), axis=0)
                    top_indices = np.argsort(mean_abs)[::-1][:5]
                    lines.append(f"")
                    lines.append(f"Top 5 features by mean |SHAP value|: {', '.join([f'Feature {i}' for i in top_indices])}")
            except Exception:
                pass
            return "\n".join(lines)
        return "SHAP analysis was not performed for this experiment set."

    def _evidence_context_section(self) -> str:
        context = self._evidence_context()
        if not context:
            return ""
        lines = [
            f"Evidence mode: `{context.get('evidence_mode', 'unknown')}`.",
            f"Verification level: `{context.get('verification_level', 'unknown')}`.",
            f"Publication-grade flag: `{context.get('publication_grade', False)}`.",
            f"Dataset publication-grade flag: `{context.get('dataset_publication_grade', False)}`.",
            f"Candidate-library publication-grade flag: `{context.get('candidate_library_publication_grade', False)}`.",
        ]
        if context.get("source_columns_is_smoke_only"):
            lines.append(
                "This is a source-columns smoke-only package: DOI and molecule evidence were accepted from input columns rather than rechecked through external services."
            )
        if context.get("metric_scope") == "training_only":
            lines.append("Model metrics in this package are training-only diagnostics.")
        return "\n".join(lines)

    def _evidence_context(self) -> dict[str, Any]:
        value = self.artifacts.get("evidence_context")
        return value if isinstance(value, dict) else {}

    def _has_training_only_metrics(self) -> bool:
        context = self._evidence_context()
        if context.get("metric_scope") == "training_only":
            return True
        return any(
            row.get("metrics", {}).get("metric_scope") == "training_only"
            for row in self.results
        )
